// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace gameboyEmulator.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("OpCodeSkeletonGenerator")]
    public partial class OpCodeSkeletonGeneratorFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OpCodeSkeletonGenerator.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "OpCodeSkeletonGenerator", "\tIn order to generate opCode skeletons\r\n\tAs an emulation noob\r\n\tI want to create " +
                    "switch cases with as much info about the opcode as possible", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate Opcode Cases")]
        public virtual void GenerateOpcodeCases()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate Opcode Cases", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Mneumonic",
                        "Bytes",
                        "Cycles",
                        "Flags"});
            table1.AddRow(new string[] {
                        "NOP",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD BC,d16",
                        "3",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (BC),A",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC BC",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC B",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC B",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD B,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RLCA",
                        "1",
                        "4",
                        "0 0 0 C"});
            table1.AddRow(new string[] {
                        "LD (a16),SP",
                        "3",
                        "20",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD HL,BC",
                        "1",
                        "8",
                        "- 0 H C"});
            table1.AddRow(new string[] {
                        "LD A,(BC)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DEC BC",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC C",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC C",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD C,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RRCA",
                        "1",
                        "4",
                        "0 0 0 C"});
            table1.AddRow(new string[] {
                        "STOP 0",
                        "2",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD DE,d16",
                        "3",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (DE),A",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC DE",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC D",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC D",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD D,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RLA",
                        "1",
                        "4",
                        "0 0 0 C"});
            table1.AddRow(new string[] {
                        "JR r8",
                        "2",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD HL,DE",
                        "1",
                        "8",
                        "- 0 H C"});
            table1.AddRow(new string[] {
                        "LD A,(DE)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DEC DE",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC E",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC E",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD E,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RRA",
                        "1",
                        "4",
                        "0 0 0 C"});
            table1.AddRow(new string[] {
                        "JR NZ,r8",
                        "2",
                        "12~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD HL,d16",
                        "3",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL+),A",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC HL",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC H",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC H",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD H,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DAA",
                        "1",
                        "4",
                        "Z - 0 C"});
            table1.AddRow(new string[] {
                        "JR Z,r8",
                        "2",
                        "12~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD HL,HL",
                        "1",
                        "8",
                        "- 0 H C"});
            table1.AddRow(new string[] {
                        "LD A,(HL+)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DEC HL",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC L",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC L",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD L,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "CPL",
                        "1",
                        "4",
                        "- 1 1 -"});
            table1.AddRow(new string[] {
                        "JR NC,r8",
                        "2",
                        "12~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD SP,d16",
                        "3",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL-),A",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC SP",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC (HL)",
                        "1",
                        "12",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC (HL)",
                        "1",
                        "12",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD (HL),d8",
                        "2",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "SCF",
                        "1",
                        "4",
                        "- 0 0 1"});
            table1.AddRow(new string[] {
                        "JR C,r8",
                        "2",
                        "12~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD HL,SP",
                        "1",
                        "8",
                        "- 0 H C"});
            table1.AddRow(new string[] {
                        "LD A,(HL-)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DEC SP",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "INC A",
                        "1",
                        "4",
                        "Z 0 H -"});
            table1.AddRow(new string[] {
                        "DEC A",
                        "1",
                        "4",
                        "Z 1 H -"});
            table1.AddRow(new string[] {
                        "LD A,d8",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "CCF",
                        "1",
                        "4",
                        "- 0 0 C"});
            table1.AddRow(new string[] {
                        "LD B,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD B,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD C,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD D,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD E,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD H,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD L,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),B",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),C",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),D",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),E",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),H",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),L",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "HALT",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (HL),A",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,B",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,C",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,D",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,E",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,H",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,L",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,(HL)",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,A",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD A,B",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,C",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,D",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,E",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,H",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,L",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,(HL)",
                        "1",
                        "8",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADD A,A",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,B",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,C",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,D",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,E",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,H",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,L",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,(HL)",
                        "1",
                        "8",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "ADC A,A",
                        "1",
                        "4",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "SUB B",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB C",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB D",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB E",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB H",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB L",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB (HL)",
                        "1",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SUB A",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,B",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,C",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,D",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,E",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,H",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,L",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,(HL)",
                        "1",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "SBC A,A",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "AND B",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND C",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND D",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND E",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND H",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND L",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND (HL)",
                        "1",
                        "8",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "AND A",
                        "1",
                        "4",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "XOR B",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR C",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR D",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR E",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR H",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR L",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR (HL)",
                        "1",
                        "8",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "XOR A",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR B",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR C",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR D",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR E",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR H",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR L",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR (HL)",
                        "1",
                        "8",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "OR A",
                        "1",
                        "4",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "CP B",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP C",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP D",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP E",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP H",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP L",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP (HL)",
                        "1",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "CP A",
                        "1",
                        "4",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "RET NZ",
                        "1",
                        "20~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "POP BC",
                        "1",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "JP NZ,a16",
                        "3",
                        "16~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "JP a16",
                        "3",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "CALL NZ,a16",
                        "3",
                        "24~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "PUSH BC",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD A,d8",
                        "2",
                        "8",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "RST 00H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RET Z",
                        "1",
                        "20~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RET",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "JP Z,a16",
                        "3",
                        "16~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "PREFIX CB",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "CALL Z,a16",
                        "3",
                        "24~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "CALL a16",
                        "3",
                        "24",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADC A,d8",
                        "2",
                        "8",
                        "Z 0 H C"});
            table1.AddRow(new string[] {
                        "RST 08H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RET NC",
                        "1",
                        "20~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "POP DE",
                        "1",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "JP NC,a16",
                        "3",
                        "16~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "CALL NC,a16",
                        "3",
                        "24~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "PUSH DE",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "SUB d8",
                        "2",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "RST 10H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RET C",
                        "1",
                        "20~8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "RETI",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "JP C,a16",
                        "3",
                        "16~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "CALL C,a16",
                        "3",
                        "24~12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "SBC A,d8",
                        "2",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "RST 18H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LDH (a8),A",
                        "2",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "POP HL",
                        "1",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (C),A",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "PUSH HL",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "AND d8",
                        "2",
                        "8",
                        "Z 0 1 0"});
            table1.AddRow(new string[] {
                        "RST 20H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "ADD SP,r8",
                        "2",
                        "16",
                        "0 0 H C"});
            table1.AddRow(new string[] {
                        "JP (HL)",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD (a16),A",
                        "3",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "XOR d8",
                        "2",
                        "8",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "RST 28H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LDH A,(a8)",
                        "2",
                        "12",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "POP AF",
                        "1",
                        "12",
                        "Z N H C"});
            table1.AddRow(new string[] {
                        "LD A,(C)",
                        "2",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "DI",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "PUSH AF",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "OR d8",
                        "2",
                        "8",
                        "Z 0 0 0"});
            table1.AddRow(new string[] {
                        "RST 30H",
                        "1",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD HL,SP+r8",
                        "2",
                        "12",
                        "0 0 H C"});
            table1.AddRow(new string[] {
                        "LD SP,HL",
                        "1",
                        "8",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "LD A,(a16)",
                        "3",
                        "16",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "EI",
                        "1",
                        "4",
                        "- - - -"});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "CP d8",
                        "2",
                        "8",
                        "Z 1 H C"});
            table1.AddRow(new string[] {
                        "RST 38H",
                        "1",
                        "16",
                        "- - - -"});
#line 7
 testRunner.Given("a table of opcode details", ((string)(null)), table1, "Given ");
#line 265
 testRunner.Then("give me the cases in C Sharp", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
